### ISSUE TITLE
[BUG]: zenml up fails to launch dashboard

### ISSUE THREAD

**Issue by fschlz** [zenml-io/zenml#1259] opened 2023-01-25 09:40 UTC
### System Information

ZenML version: 0.32.0
Install path: /Users/fschulz/.pyenv/versions/3.10.8/lib/python3.10/site-packages/zenml
Python version: 3.10.8
Platform information: {'os': 'mac', 'mac_version': '13.1'}
Environment: native
Integrations: ['azure', 'github', 'kaniko']

[installed-python-packages.txt](https://github.com/zenml-io/zenml/files/10498005/installed-python-packages.txt)

### What happened?

I ran the command, and it produces an internal server error

### Reproduction steps

1.
2.
3.
...

### Relevant log output

```shell
❯ zenml up                     
The local ZenML server is already configured with the same parameters.
Connecting ZenML to the 'local' local ZenML server (http://127.0.0.1:8237).
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /Users/fschulz/.pyenv/versions/3.10.8/lib/python3.10/site-packages/zenml/zen_stores/base_zen_sto │
│ re.py:109 in __init__                                                                            │
│                                                                                                  │
│   106 │   │   super().__init__(**kwargs)                                                         │
│   107 │   │                                                                                      │
│   108 │   │   try:                                                                               │
│ ❱ 109 │   │   │   self._initialize()                                                             │
│   110 │   │   except Exception as e:                                                             │
│   111 │   │   │   raise RuntimeError(                                                            │
│   112 │   │   │   │   f"Error initializing {self.type.value} store with URL "                    │
│                                                                                                  │
│ /Users/fschulz/.pyenv/versions/3.10.8/lib/python3.10/site-packages/zenml/zen_stores/rest_zen_sto │
│ re.py:360 in _initialize                                                                         │
│                                                                                                  │
│    357 │   def _initialize(self) -> None:                                                        │
│    358 │   │   """Initialize the REST store."""                                                  │
│    359 │   │   client_version = zenml.__version__                                                │
│ ❱  360 │   │   server_version = self.get_store_info().version                                    │
│    361 │   │                                                                                     │
│    362 │   │   if not DISABLE_CLIENT_SERVER_MISMATCH_WARNING and (                               │
│    363 │   │   │   server_version != client_version                                              │
│                                                                                                  │
│ /Users/fschulz/.pyenv/versions/3.10.8/lib/python3.10/site-packages/zenml/zen_stores/rest_zen_sto │
│ re.py:381 in get_store_info                                                                      │
│                                                                                                  │
│    378 │   │   Returns:                                                                          │
│    379 │   │   │   Information about the server.                                                 │
│    380 │   │   """                                                                               │
│ ❱  381 │   │   body = self.get(INFO)                                                             │
│    382 │   │   return ServerModel.parse_obj(body)                                                │
│    383 │                                                                                         │
│    384 │   # ------                                                                              │
│                                                                                                  │
│ /Users/fschulz/.pyenv/versions/3.10.8/lib/python3.10/site-packages/zenml/zen_stores/rest_zen_sto │
│ re.py:1793 in get                                                                                │
│                                                                                                  │
│   1790 │   │   │   The response body.                                                            │
│   1791 │   │   """                                                                               │
│   1792 │   │   logger.debug(f"Sending GET request to {path}...")                                 │
│ ❱ 1793 │   │   return self._request(                                                             │
│   1794 │   │   │   "GET", self.url + API + VERSION_1 + path, params=params, **kwargs             │
│   1795 │   │   )                                                                                 │
│   1796                                                                                           │
│                                                                                                  │
│ /Users/fschulz/.pyenv/versions/3.10.8/lib/python3.10/site-packages/zenml/zen_stores/rest_zen_sto │
│ re.py:1754 in _request                                                                           │
│                                                                                                  │
│   1751 │   │   """                                                                               │
│   1752 │   │   params = {k: str(v) for k, v in params.items()} if params else {}                 │
│   1753 │   │   try:                                                                              │
│ ❱ 1754 │   │   │   return self._handle_response(                                                 │
│   1755 │   │   │   │   self.session.request(                                                     │
│   1756 │   │   │   │   │   method,                                                               │
│   1757 │   │   │   │   │   url,                                                                  │
│                                                                                                  │
│ /Users/fschulz/.pyenv/versions/3.10.8/lib/python3.10/site-packages/zenml/zen_stores/rest_zen_sto │
│ re.py:1727 in _handle_response                                                                   │
│                                                                                                  │
│   1724 │   │   │   │   response_msg = response.text                                              │
│   1725 │   │   │   raise RuntimeError(response_msg)                                              │
│   1726 │   │   elif response.status_code == 500:                                                 │
│ ❱ 1727 │   │   │   raise RuntimeError(response.text)                                             │
│   1728 │   │   else:                                                                             │
│   1729 │   │   │   raise RuntimeError(                                                           │
│   1730 │   │   │   │   "Error retrieving from API. Got response "                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Internal Server Error

The above exception was the direct cause of the following exception:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /Users/fschulz/.pyenv/versions/3.10.8/bin/zenml:8 in <module>                                    │
│                                                                                                  │
│   5 from zenml.cli.cli import cli                                                                │
│   6 if __name__ == '__main__':                                                                   │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 8 │   sys.exit(cli())                                                                          │
│   9                                                                                              │
│                                                                                                  │
│ /Users/fschulz/.pyenv/versions/3.10.8/lib/python3.10/site-packages/click/core.py:1130 in         │
│ __call__                                                                                         │
│                                                                                                  │
│   1127 │                                                                                         │
│   1128 │   def __call__(self, *args: t.Any, **kwargs: t.Any) -> t.Any:                           │
│   1129 │   │   """Alias for :meth:`main`."""                                                     │
│ ❱ 1130 │   │   return self.main(*args, **kwargs)                                                 │
│   1131                                                                                           │
│   1132                                                                                           │
│   1133 class Command(BaseCommand):                                                               │
│                                                                                                  │
│ /Users/fschulz/.pyenv/versions/3.10.8/lib/python3.10/site-packages/click/core.py:1055 in main    │
│                                                                                                  │
│   1052 │   │   try:                                                                              │
│   1053 │   │   │   try:                                                                          │
│   1054 │   │   │   │   with self.make_context(prog_name, args, **extra) as ctx:                  │
│ ❱ 1055 │   │   │   │   │   rv = self.invoke(ctx)                                                 │
│   1056 │   │   │   │   │   if not standalone_mode:                                               │
│   1057 │   │   │   │   │   │   return rv                                                         │
│   1058 │   │   │   │   │   # it's not safe to `ctx.exit(rv)` here!                               │
│                                                                                                  │
│ /Users/fschulz/.pyenv/versions/3.10.8/lib/python3.10/site-packages/click/core.py:1657 in invoke  │
│                                                                                                  │
│   1654 │   │   │   │   super().invoke(ctx)                                                       │
│   1655 │   │   │   │   sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)                    │
│   1656 │   │   │   │   with sub_ctx:                                                             │
│ ❱ 1657 │   │   │   │   │   return _process_result(sub_ctx.command.invoke(sub_ctx))               │
│   1658 │   │                                                                                     │
│   1659 │   │   # In chain mode we create the contexts step by step, but after the                │
│   1660 │   │   # base command has been invoked.  Because at that point we do not                 │
│                                                                                                  │
│ /Users/fschulz/.pyenv/versions/3.10.8/lib/python3.10/site-packages/click/core.py:1404 in invoke  │
│                                                                                                  │
│   1401 │   │   │   echo(style(message, fg="red"), err=True)                                      │
│   1402 │   │                                                                                     │
│   1403 │   │   if self.callback is not None:                                                     │
│ ❱ 1404 │   │   │   return ctx.invoke(self.callback, **ctx.params)                                │
│   1405 │                                                                                         │
│   1406 │   def shell_complete(self, ctx: Context, incomplete: str) -> t.List["CompletionItem"]:  │
│   1407 │   │   """Return a list of completions for the incomplete value. Looks                   │
│                                                                                                  │
│ /Users/fschulz/.pyenv/versions/3.10.8/lib/python3.10/site-packages/click/core.py:760 in invoke   │
│                                                                                                  │
│    757 │   │                                                                                     │
│    758 │   │   with augment_usage_errors(__self):                                                │
│    759 │   │   │   with ctx:                                                                     │
│ ❱  760 │   │   │   │   return __callback(*args, **kwargs)                                        │
│    761 │                                                                                         │
│    762 │   def forward(                                                                          │
│    763 │   │   __self, __cmd: "Command", *args: t.Any, **kwargs: t.Any  # noqa: B902             │
│                                                                                                  │
│ /Users/fschulz/.pyenv/versions/3.10.8/lib/python3.10/site-packages/zenml/cli/server.py:252 in up │
│                                                                                                  │
│   249 │   │   │   │   connect = True                                                             │
│   250 │   │   │                                                                                  │
│   251 │   │   │   if connect:                                                                    │
│ ❱ 252 │   │   │   │   deployer.connect_to_server(                                                │
│   253 │   │   │   │   │   LOCAL_ZENML_SERVER_NAME,                                               │
│   254 │   │   │   │   │   DEFAULT_USERNAME,                                                      │
│   255 │   │   │   │   │   DEFAULT_PASSWORD,                                                      │
│                                                                                                  │
│ /Users/fschulz/.pyenv/versions/3.10.8/lib/python3.10/site-packages/zenml/zen_server/deploy/deplo │
│ yer.py:267 in connect_to_server                                                                  │
│                                                                                                  │
│   264 │   │   │   f"{provider_name} ZenML server ({store_config.url})."                          │
│   265 │   │   )                                                                                  │
│   266 │   │                                                                                      │
│ ❱ 267 │   │   gc.set_store(store_config)                                                         │
│   268 │   │                                                                                      │
│   269 │   │   logger.info(                                                                       │
│   270 │   │   │   f"Connected ZenML to the '{server_name}' "                                     │
│                                                                                                  │
│ /Users/fschulz/.pyenv/versions/3.10.8/lib/python3.10/site-packages/zenml/config/global_config.py │
│ :625 in set_store                                                                                │
│                                                                                                  │
│   622 │   │   │   event=AnalyticsEvent.INITIALIZED_STORE,                                        │
│   623 │   │   │   metadata={"store_type": config.type.value},                                    │
│   624 │   │   ):                                                                                 │
│ ❱ 625 │   │   │   self._configure_store(config, skip_default_registrations, **kwargs)            │
│   626 │   │   │   logger.info("Updated the global store configuration.")                         │
│   627 │   │   │                                                                                  │
│   628 │   │   │   if self.zen_store.type == StoreType.REST:                                      │
│                                                                                                  │
│ /Users/fschulz/.pyenv/versions/3.10.8/lib/python3.10/site-packages/zenml/config/global_config.py │
│ :391 in _configure_store                                                                         │
│                                                                                                  │
│   388 │   │   """                                                                                │
│   389 │   │   from zenml.zen_stores.base_zen_store import BaseZenStore                           │
│   390 │   │                                                                                      │
│ ❱ 391 │   │   store = BaseZenStore.create_store(                                                 │
│   392 │   │   │   config, skip_default_registrations, **kwargs                                   │
│   393 │   │   )                                                                                  │
│   394 │   │   if self.store != store.config or not self._zen_store:                              │
│                                                                                                  │
│ /Users/fschulz/.pyenv/versions/3.10.8/lib/python3.10/site-packages/zenml/zen_stores/base_zen_sto │
│ re.py:206 in create_store                                                                        │
│                                                                                                  │
│   203 │   │   """                                                                                │
│   204 │   │   logger.debug(f"Creating store with config '{config}'...")                          │
│   205 │   │   store_class = BaseZenStore.get_store_class(config.type)                            │
│ ❱ 206 │   │   store = store_class(                                                               │
│   207 │   │   │   config=config,                                                                 │
│   208 │   │   │   skip_default_registrations=skip_default_registrations,                         │
│   209 │   │   │   **kwargs,                                                                      │
│                                                                                                  │
│ /Users/fschulz/.pyenv/versions/3.10.8/lib/python3.10/site-packages/zenml/zen_stores/base_zen_sto │
│ re.py:111 in __init__                                                                            │
│                                                                                                  │
│   108 │   │   try:                                                                               │
│   109 │   │   │   self._initialize()                                                             │
│   110 │   │   except Exception as e:                                                             │
│ ❱ 111 │   │   │   raise RuntimeError(                                                            │
│   112 │   │   │   │   f"Error initializing {self.type.value} store with URL "                    │
│   113 │   │   │   │   f"'{self.url}': {str(e)}"                                                  │
│   114 │   │   │   ) from e                                                                       │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Error initializing rest store with URL 'http://127.0.0.1:8237': Internal Server Error
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by htahir1** [comment] 2023-01-25 10:31
@fschlz Did you run any `zenml` command before running `zenml up`? We found a bug (and are fixing it asap) that if you dont run any zenml command the alembic migrations dont run, causing weird behavior when you did `zenml up`. 

Maybe try doing `zenml stack list` or something before running `zenml up` and theres a chance this might fix it.

If that doesnt work, can you try doing :

1. `zenml up`
2. see error
3. `cat  ~/.config/zenml/zen_server/local/service.log`
4. Copy the latest logs and paste them here

**Comment by AlexejPenner** [comment] 2023-01-25 13:37
Thanks @fschlz for raising this. I was able to reproduce this on my machine. Here is the fix for it. We should be releasing this soon. In the meantime, try Hamzas workaround.

**Comment by fschlz** [comment] 2023-01-25 14:14
@htahir1 LOL! Ok, that worked. Thanks!

However, I noticed you mentioned `~/.config/zenml` here and in other tickets.
I do not have such a `zenml` folder, though.
Didn't notice any info about having to create it, either.

**Comment by htahir1** [comment] 2023-01-25 14:27
@fschlz In case of a Mac, its at `/Users/fschulz/Library/Application Support/zenml`

**Comment by AlexejPenner** [comment] 2023-01-27 09:41
@fschlz we have fixed the underlying issue in our most recent release 0.32.1. I would close this issue here. If you do run into this again, please do reopen and let us know.

**Closed by AlexejPenner** 2023-01-27 09:41 UTC
Labels: bug

**Comment by jonasmmiguel** [comment] 2023-06-04 09:52
I ran into the same problem in ZenML 0.40.1, although I unfortunately cannot reproduce the bug anymore. 

Doing `zenml disconnect` before `zenml up` solved it for me.

**Comment by AlexejPenner** [comment] 2023-06-04 19:22
If you run into this again, feel free to post the stacktrace here. We’ll try to look into this and see if we find a way to reproduce this in 0.40.1

**Comment by duarteocarmo** [comment] 2023-07-10 08:09
Had a weird bug here as well - 

> Doing zenml disconnect before zenml up solved it for me.

☝🏻  solved it for me!
