### ISSUE TITLE
[BUG]: zenml-server frontend error when entering correct kaniko config

### ISSUE THREAD

**Issue by matthiasValuecloud** [zenml-io/zenml#1717] opened 2023-07-26 11:11 UTC
### System Information

ZENML_LOCAL_VERSION: 0.41.0
ZENML_SERVER_VERSION: 0.42.1
ZENML_SERVER_DATABASE: mysql
ZENML_SERVER_DEPLOYMENT_TYPE: kubernetes
ZENML_CONFIG_DIR: <xxx>
ZENML_LOCAL_STORE_DIR: <xxx>
ZENML_SERVER_URL: <xxx>
ZENML_ACTIVE_REPOSITORY_ROOT: None
PYTHON_VERSION: 3.8.10
ENVIRONMENT: native
SYSTEM_INFO: {'os': 'linux', 'linux_distro': 'ubuntu', 'linux_distro_like': 'debian', 'linux_distro_version': '20.04'}
ACTIVE_WORKSPACE: default
ACTIVE_STACK: kubeflow
ACTIVE_USER: default
TELEMETRY_STATUS: enabled
ANALYTICS_CLIENT_ID: e54455a1-4379-49f3-98e3-3d1fea19f0c6
ANALYTICS_USER_ID: 8dd9f6a4-e406-4072-b9b6-b5fa8b82e841
ANALYTICS_SERVER_ID: 00f248ad-ea23-4b8c-9066-3dd84d092fdf
INTEGRATIONS: ['kaniko', 'kubeflow', 'kubernetes', 'mlflow', 'scipy', 'seldon', 'sklearn', 'tensorboard', 'tensorflow']
PACKAGES: {'zope.interface': '6.0', 'zope.event': '5.0', 'zipp': '3.15.0', 'zenml': '0.41.0', 'yarl': '1.9.2', 'wrapt': '1.15.0', 'widgetsnbextension': 
'3.6.4', 'werkzeug': '2.3.6', 'websocket-client': '1.6.1', 'webencodings': '0.5.1', 'wcwidth': '0.2.6', 'validators': '0.18.2', 'uvloop': '0.17.0', 'uvicorn':
'0.23.1', 'urllib3': '1.26.16', 'uritemplate': '3.0.1', 'tzdata': '2023.3', 'typing-extensions': '4.7.1', 'typer': '0.9.0', 'tritonclient': '2.35.0', 
'traitlets': '5.9.0', 'tqdm': '4.65.0', 'tornado': '6.3.2', 'tinycss2': '1.2.1', 'threadpoolctl': '3.1.0', 'tf-estimator-nightly': '2.8.0.dev2021122109', 
'terminado': '0.17.1', 'termcolor': '2.3.0', 'tensorflow': '2.8.0', 'tensorflow-io': '0.24.0', 'tensorflow-io-gcs-filesystem': '0.32.0', 'tensorboard': 
'2.8.0', 'tensorboard-plugin-wit': '1.8.1', 'tensorboard-data-server': '0.6.1', 'tabulate': '0.9.0', 'strip-hints': '0.1.10', 'starlette': '0.30.0', 
'starlette-exporter': '0.16.0', 'stack-data': '0.6.2', 'sqlparse': '0.4.4', 'sqlmodel': '0.0.8', 'sqlalchemy2-stubs': '0.0.2a34', 'sqlalchemy': '1.4.41', 
'sqlalchemy-utils': '0.38.3', 'soupsieve': '2.4.1', 'sniffio': '1.3.0', 'smmap': '5.0.0', 'slicer': '0.0.7', 'shap': '0.42.1', 'send2trash': '1.8.2', 'scipy':
'1.10.1', 'scikit-learn': '1.2.0', 's3transfer': '0.6.1', 's3fs': '2023.6.0', 'rsa': '4.9', 'rpds-py': '0.8.8', 'rich': '12.6.0', 'rfc3986-validator': 
'0.1.1', 'rfc3339-validator': '0.1.4', 'requests': '2.31.0', 'requests-toolbelt': '0.10.1', 'requests-oauthlib': '1.3.1', 'referencing': '0.29.1', 
'querystring-parser': '1.2.4', 'pyzmq': '25.1.0', 'pyyaml': '5.4.1', 'pytz': '2022.7.1', 'python-terraform': '0.10.1', 'python-rapidjson': '1.10', 
'python-json-logger': '2.0.7', 'python-dotenv': '0.21.0', 'python-dateutil': '2.8.2', 'pyrsistent': '0.19.3', 'pyparsing': '2.4.7', 'pymysql': '1.0.3', 
'pygments': '2.15.1', 'pydantic': '1.10.11', 'pycparser': '2.21', 'pyasn1': '0.5.0', 'pyasn1-modules': '0.3.0', 'pyarrow': '11.0.0', 'py-grpc-prometheus': 
'0.7.0', 'pure-eval': '0.2.2', 'ptyprocess': '0.7.0', 'psutil': '5.9.5', 'protobuf': '3.20.3', 'prompt-toolkit': '3.0.39', 'prometheus-client': '0.17.0', 
'platformdirs': '3.8.1', 'pkgutil-resolve-name': '1.3.10', 'pickleshare': '0.7.5', 'passlib': '1.7.4', 'parso': '0.8.3', 'pandocfilters': '1.5.0', 'pandas': 
'2.0.3', 'packaging': '23.1', 'overrides': '7.3.1', 'orjson': '3.9.2', 'opt-einsum': '3.3.0', 'numpy': '1.24.4', 'numba': '0.57.1', 'notebook': '6.5.4', 
'notebook-shim': '0.2.3', 'nest-asyncio': '1.5.6', 'nbformat': '5.9.0', 'nbconvert': '7.6.0', 'nbclient': '0.8.0', 'nbclassic': '1.0.0', 'multidict': '6.0.4',
'mlserver': '1.3.5', 'mlserver-mlflow': '1.3.5', 'mlflow': '2.2.2', 'mistune': '3.0.1', 'matplotlib': '3.7.2', 'matplotlib-inline': '0.1.6', 'markupsafe': 
'2.1.3', 'markdown': '3.4.3', 'llvmlite': '0.40.1', 'libclang': '16.0.0', 'kubernetes': '18.20.0', 'kiwisolver': '1.4.4', 'kfp': '1.8.16', 'kfp-server-api': 
'1.8.5', 'kfp-pipeline-spec': '0.1.16', 'keras': '2.8.0', 'keras-preprocessing': '1.1.2', 'kafka-python': '2.0.2', 'jupyterlab-widgets': '1.1.4', 
'jupyterlab-pygments': '0.2.2', 'jupyter-server': '2.7.0', 'jupyter-server-terminals': '0.4.4', 'jupyter-events': '0.6.3', 'jupyter-core': '5.3.1', 
'jupyter-client': '8.3.0', 'jsonschema': '3.2.0', 'jsonschema-specifications': '2023.6.1', 'joblib': '1.3.1', 'jmespath': '1.0.1', 'jinja2': '3.1.2', 'jedi': 
'0.18.2', 'itsdangerous': '2.1.2', 'isodate': '0.6.1', 'ipywidgets': '7.7.5', 'ipython': '8.12.2', 'ipython-genutils': '0.2.0', 'ipykernel': '6.24.0', 
'importlib-resources': '5.12.0', 'importlib-metadata': '6.7.0', 'httplib2': '0.19.1', 'h11': '0.14.0', 'h5py': '3.9.0', 'gunicorn': '20.1.0', 'grpcio': 
'1.56.0', 'greenlet': '2.0.2', 'googleapis-common-protos': '1.59.1', 'google-resumable-media': '2.5.0', 'google-pasta': '0.2.0', 'google-crc32c': '1.5.0', 
'google-cloud-storage': '2.10.0', 'google-cloud-core': '2.3.3', 'google-auth': '2.21.0', 'google-auth-oauthlib': '0.4.6', 'google-auth-httplib2': '0.1.0', 
'google-api-python-client': '1.12.11', 'google-api-core': '2.11.1', 'gitpython': '3.1.31', 'gitdb': '4.0.10', 'geventhttpclient': '2.0.2', 'gevent': '23.7.0',
'gast': '0.5.4', 'fsspec': '2023.6.0', 'frozenlist': '1.3.3', 'fonttools': '4.41.0', 'flatbuffers': '23.5.26', 'flask': '2.3.2', 'fire': '0.5.0', 
'fastjsonschema': '2.17.1', 'fastapi': '0.89.1', 'executing': '1.2.0', 'exceptiongroup': '1.1.2', 'dotenv-cli': '3.1.0', 'docstring-parser': '0.15', 'docker':
'6.1.3', 'distro': '1.8.0', 'deprecated': '1.2.14', 'defusedxml': '0.7.1', 'decorator': '5.1.1', 'debugpy': '1.6.7', 'databricks-cli': '0.17.7', 'cycler': 
'0.11.0', 'contourpy': '1.1.0', 'commonmark': '0.9.1', 'comm': '0.1.3', 'cloudpickle': '2.2.1', 'click': '8.1.4', 'click-params': '0.3.0', 
'charset-normalizer': '3.1.0', 'cffi': '1.15.1', 'cachetools': '5.3.1', 'brotli': '1.0.9', 'botocore': '1.29.161', 'blinker': '1.6.2', 'bleach': '6.0.0', 
'beautifulsoup4': '4.12.2', 'backoff': '1.10.0', 'backcall': '0.2.0', 'azure-mgmt-resource': '23.0.1', 'azure-mgmt-core': '1.4.0', 'azure-core': '1.27.1', 
'azure-common': '1.1.28', 'attrs': '23.1.0', 'async-timeout': '4.0.2', 'astunparse': '1.6.3', 'asttokens': '2.2.1', 'argon2-cffi': '21.3.0', 
'argon2-cffi-bindings': '21.2.0', 'anyio': '3.7.1', 'analytics-python': '1.4.post1', 'alembic': '1.8.1', 'aiosignal': '1.3.1', 'aiokafka': '0.8.1', 
'aioitertools': '0.11.0', 'aiohttp': '3.8.4', 'aiofiles': '23.1.0', 'aiobotocore': '2.5.2', 'absl-py': '1.4.0', 'xkit': '0.0.0', 'wheel': '0.34.2', 'wadllib':
'1.3.3', 'usb-creator': '0.3.7', 'unattended-upgrades': '0.1', 'ufw': '0.36', 'ubuntu-drivers-common': '0.0.0', 'ubuntu-advantage-tools': '27.10', 
'systemd-python': '234', 'six': '1.14.0', 'simplejson': '3.16.0', 'setuptools': '45.2.0', 'secretstorage': '2.3.1', 'requests-unixsocket': '0.2.0', 
'reportlab': '3.5.34', 'pyxdg': '0.26', 'python-debian': '0.1.36ubuntu1', 'python-apt': '2.0.0+ubuntu0.20.4.8', 'pyrfc3339': '1.1', 'pynacl': '1.3.0', 
'pymacaroons': '0.13.0', 'pyjwt': '1.7.1', 'pygobject': '3.36.0', 'pycups': '1.9.73', 'pycairo': '1.16.2', 'pip': '20.0.2', 'pillow': '7.0.0', 'pexpect': 
'4.6.0', 'paramiko': '2.6.0', 'olefile': '0.46', 'oauthlib': '3.1.0', 'netifaces': '0.10.4', 'monotonic': '1.5', 'mako': '1.1.0', 'macaroonbakery': '1.3.1', 
'louis': '3.12.0', 'lockfile': '0.12.2', 'lazr.uri': '1.0.3', 'lazr.restfulclient': '0.14.2', 'launchpadlib': '1.10.13', 'language-selector': '0.1', 
'keyring': '18.0.1', 'idna': '2.8', 'future': '0.18.2', 'fasteners': '0.14.1', 'entrypoints': '0.3', 'duplicity': '0.8.12.0', 'distro-info': '0.23ubuntu1', 
'defer': '1.0.6', 'dbus-python': '1.2.16', 'cupshelpers': '1.0', 'cryptography': '2.8', 'command-not-found': '0.3', 'colorama': '0.4.3', 'chardet': '3.0.4', 
'certifi': '2019.11.28', 'brlapi': '0.7.0', 'bcrypt': '3.1.7', 'apturl': '0.5.2'}

CURRENT STACK

Name: kubeflow
ID: 689054d1-cbb8-48c3-9869-69dacc44edea
Shared: Yes
User: default / 8dd9f6a4-e406-4072-b9b6-b5fa8b82e841
Workspace: default / 0cb99ccf-425f-4b52-8b2e-758b93ff4d56

ORCHESTRATOR: kubeflow_electric_boogaloo

Name: kubeflow_electric_boogaloo
ID: b220ea51-022b-4b25-bf2f-a51a16211094
Type: orchestrator
Flavor: kubeflow
Configuration: {'synchronous': False, 'timeout': 1200, 'client_args': {}, 'client_username': '********', 'client_password': '********', 'user_namespace': 
'<xxx>', 'node_selectors': {}, 'node_affinity': {}, 'pod_settings': KubernetesPodSettings(node_selectors={}, affinity={}, tolerations=[], 
resources={}, annotations={}), 'kubeflow_hostname': '<xxx>', 'kubeflow_namespace': 'kubeflow', 
'kubernetes_context': '', 'local': False, 'skip_local_validations': False}
Shared: Yes
User: <xxx>
Workspace: <xxx>

ARTIFACT_STORE: storage

Name: storage
ID: d421e060-2dba-4be7-b2a5-aaae98e4a48d
Type: artifact_store
Flavor: s3
Configuration: {'authentication_secret': '', 'path': '<xxx>', 'key': '********', 'secret': '********', 'token': '********', 
'client_kwargs': {'endpoint_url': '<xxx>', 'region_name': 'us-east-1'}, 'config_kwargs': {}, 's3_additional_kwargs': 
{'addressing_style': 'path'}}
Shared: Yes
User: <xxx>
Workspace:<xxx>

CONTAINER_REGISTRY: <xxx>

Name: <xxx>
ID: 6e2cfa3b-c7d0-4ed9-bacf-7812f12a890f
Type: container_registry
Flavor: default
Configuration: {'authentication_secret': 'registry-creds', 'uri': '<xxx>'}
Shared: Yes
User: <xxx>
Workspace: <xxx>

IMAGE_BUILDER: kaniko

Name: kaniko
ID: 78fe97cc-8d79-4a88-8cd8-f10cfe62e2fc
Type: image_builder
Flavor: kaniko
Configuration: {'kubernetes_context': 'kaniko-access', 'kubernetes_namespace': '<xxx>', 'executor_image': 
'gcr.io/kaniko-project/executor:v1.9.1', 'env': [], 'env_from': [], 'volume_mounts': [{'name': 'docker-config', 'mountPath': '/kaniko/.docker/'}], 'volumes': 
[{'name': 'docker-config', 'secret': {'secretName': 'kaniko-executor-config'}}], 'service_account_name': '', 'store_context_in_artifact_store': False, 
'executor_args': ['']}
Shared: Yes
User: <xxx>
Workspace: <xxx>

### What happened?

Kaniko configuration as retrieved via
`` zenml image-builder describe``

![grafik](https://github.com/zenml-io/zenml/assets/116789801/e5954da3-fa1a-4422-8b4b-10dc0d1d7719)

Expected behaviour:
- when navigating to https://<url>/workspaces/<workspace>/components/image_builder/<image-builder-id>/configuration i get the normal configuration page for Kaniko

Observed behaviour:
- white page with 2 errors:
    TypeError: y.map is not a function
   Uncaught TypeError: y.map is not a function

### Reproduction steps

1.
2.
3.
...

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Cahllagerfeld** [comment] 2023-08-08 13:16
Hey @matthiasValuecloud, thanks for raising the issue! 
That's indeed a non-expected behavior and a bug in the dashboard. Are these the full two error messages, or are they containing a stack trace as well? In case there's a stack trace could you please also share them (although in production mode they may look a bit cryptic). 

Other than that I'm investigating on it, to get it fixed!

**Comment by strickvl** [comment] 2024-02-05 17:00
@matthiasValuecloud wondering if you're still having this problem? we're actually reworking the dashboard a lot these days so I think in any case this should be solved in due course. please let us know and otherwise we can close this issue. Thanks!

**Comment by htahir1** [comment] 2024-08-26 16:54
Closing due to staleness

**Closed by htahir1** 2024-08-26 16:54 UTC
Labels: bug
