### ISSUE TITLE
[BUG]: Cannot use `zenml init` with templates even after installing `zenml[templates]`

### ISSUE THREAD

**Issue by vikramcee** [zenml-io/zenml#2575] opened 2024-04-01 22:06 UTC
### System Information

```
ZENML_LOCAL_VERSION: 0.56.2
ZENML_SERVER_VERSION: 0.56.2
ZENML_SERVER_DATABASE: sqlite
ZENML_SERVER_DEPLOYMENT_TYPE: other
ZENML_CONFIG_DIR: [redacted]/.config/zenml
ZENML_LOCAL_STORE_DIR: [redacted]/.config/zenml/local_stores
ZENML_SERVER_URL: sqlite:////[redacted]/config/zenml/local_stores/default_zen_store/zenml.db
ZENML_ACTIVE_REPOSITORY_ROOT: [redacted]
PYTHON_VERSION: 3.10.14
ENVIRONMENT: native
SYSTEM_INFO: {'os': 'linux', 'linux_distro': 'rocky', 'linux_distro_like': 'rhel centos fedora', 'linux_distro_version': '8.6'}
ACTIVE_WORKSPACE: default
ACTIVE_STACK: default
ACTIVE_USER: default
TELEMETRY_STATUS: enabled
ANALYTICS_CLIENT_ID: 2b19aadf-701f-4d23-9165-a9b6a557fb18
ANALYTICS_USER_ID: 7b436f48-733f-432a-996a-b25c637e1c42
ANALYTICS_SERVER_ID: 2b19aadf-701f-4d23-9165-a9b6a557fb18
INTEGRATIONS: ['bitbucket', 'kaniko']
PACKAGES: {'gitpython': '3.1.43', 'jinja2': '3.1.3', 'mako': '1.3.2', 'markupsafe': '2.1.5', 'pyjwt': '2.7.0', 'pymysql': '1.0.3', 'pyyaml': '6.0.1', 'sqlalchemy': '1.4.41', 'sqlalchemy-utils': '0.38.3', 'aiohttp': '3.9.3', 'aiosignal': '1.3.1', 'alembic': '1.8.1', 'anyio': '4.3.0', 'arrow': '1.3.0', 'asttokens':
'2.4.1', 'async-timeout': '4.0.3', 'attrs': '23.2.0', 'azure-common': '1.1.28', 'azure-core': '1.30.1', 'azure-mgmt-core': '1.4.0', 'azure-mgmt-resource': '23.0.1', 'bcrypt': '4.0.1', 'cachetools': '5.3.3', 'certifi': '2024.2.2', 'cffi': '1.16.0', 'charset-normalizer': '3.3.2', 'click': '8.1.3', 'click-params':
'0.3.0', 'cloudpickle': '2.2.1', 'colorama': '0.4.6', 'comm': '0.2.2', 'copier': '8.1.0', 'cryptography': '42.0.5', 'decorator': '5.1.1', 'distro': '1.9.0', 'docker': '6.1.3', 'dunamai': '1.19.2', 'exceptiongroup': '1.2.0', 'executing': '2.0.1', 'fastapi': '0.99.1', 'fastapi-utils': '0.2.1', 'frozenlist': '1.4.1',
'fsspec': '2024.3.1', 'funcy': '2.0', 'gitdb': '4.0.11', 'greenlet': '3.0.3', 'h11': '0.14.0', 'httplib2': '0.19.1', 'httptools': '0.6.1', 'idna': '3.6', 'ipinfo': '5.0.1', 'ipython': '8.18.0', 'ipywidgets': '8.1.2', 'isodate': '0.6.1', 'jedi': '0.19.1', 'jinja2-ansible-filters': '1.3.2', 'jinja2-time': '0.2.0',
'jupyterlab-widgets': '3.0.10', 'markdown-it-py': '3.0.0', 'matplotlib-inline': '0.1.6', 'mdurl': '0.1.2', 'multidict': '6.0.5', 'numpy': '1.26.4', 'orjson': '3.8.14', 'packaging': '24.0', 'pandas': '2.2.1', 'parso': '0.8.3', 'passlib': '1.7.4', 'pathspec': '0.12.1', 'pexpect': '4.9.0', 'pip': '24.0', 'plumbum':
'1.8.2', 'prompt-toolkit': '3.0.36', 'psutil': '5.9.8', 'ptyprocess': '0.7.0', 'pure-eval': '0.2.2', 'pycparser': '2.22', 'pydantic': '1.10.14', 'pygments': '2.17.2', 'pyparsing': '2.4.7', 'python-dateutil': '2.9.0.post0', 'python-dotenv': '1.0.1', 'python-multipart': '0.0.9', 'pytz': '2024.1', 'pyyaml-include':
'2.0', 'questionary': '2.0.1', 'requests': '2.31.0', 'rich': '13.7.1', 'ruff': '0.3.5', 'setuptools': '69.2.0', 'six': '1.16.0', 'smmap': '5.0.1', 'sniffio': '1.3.1', 'sqlalchemy2-stubs': '0.0.2a38', 'sqlmodel': '0.0.8', 'stack-data': '0.6.3', 'starlette': '0.27.0', 'traitlets': '5.14.2', 'types-python-dateutil':
'2.9.0.20240316', 'typing-extensions': '4.10.0', 'tzdata': '2024.1', 'urllib3': '2.2.1', 'uvicorn': '0.29.0', 'uvloop': '0.19.0', 'validators': '0.18.2', 'watchfiles': '0.21.0', 'wcwidth': '0.2.13', 'websocket-client': '1.7.0', 'websockets': '12.0', 'wheel': '0.43.0', 'widgetsnbextension': '4.0.10', 'yarl': '1.9.4',
'zenml': '0.56.2'}

CURRENT STACK

Name: default
ID: 5602dd46-09e8-46ac-b4d2-40d25d5808a5
Workspace: default / 4bf523b8-b21a-4658-a231-63a8136ee050

ORCHESTRATOR: default

Name: default
ID: 291f31cb-e982-403a-8dd7-692803e5684c
Type: orchestrator
Flavor: local
Configuration: {}
Workspace: default / 4bf523b8-b21a-4658-a231-63a8136ee050

ARTIFACT_STORE: default

Name: default
ID: d5362801-b94b-4d4f-9526-7dcd98f128d9
Type: artifact_store
Flavor: local
Configuration: {'path': ''}
Workspace: default / 4bf523b8-b21a-4658-a231-63a8136ee050
```

### What happened?

I am creating a new virtual environment with python 3.10 as follows:
`conda create -n zenml python=3.10`

Then installing `zenml` as follows after activating the environment:
`pip install zenml[server,templates]`

At this point I would expect to be able to create a new `zenml` template as follows:

`zenml init --template e2e_batch` (or any other template for that matter)

BUT I am receiving the following error:

`Error: You need to install the ZenML project template requirements to use templates. Please run pip install zenml[templates] and try again.`

even though I have pip installed the package multiple times and tried `--force-reinstall` as well.

I've also tried installing both separately and in new virtual environments and I still get the same error.

Any help would be greatly appreciated.

### Reproduction steps

1. `conda create -n zenml python=3.10`
2. `conda activate zenml`
3. `pip install zenml[server,templates]`
4. `zenml init --template e2e_batch`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bcdurak** [comment] 2024-04-02 12:38
Hey @vikramcee,

Thank you for reporting this issue. 

When you execute the command `zenml init` with a template, ZenML uses `copier` in the background to render the template. Unfortunately, there is [a reported issue](https://github.com/copier-org/copier/issues/1568) with their `pyyaml-include` dependency.

Until this issue is resolved, if you want to use this template, I would suggest using the example in our repository by manually cloning the repository:

```bash
git clone git@github.com:zenml-io/zenml.git
cd zenml/examples/e2e
pip install -r requirements.txt
zenml init
```

Feel free to let me know if you have any further questions.

**Comment by bcdurak** [comment] 2024-04-10 13:14
@vikramcee Quick update: With [the release of 0.56.3](https://github.com/zenml-io/zenml/releases/tag/0.56.3), we have fixed this issue. With the new version, you can now use `zenml init --template e2e_batch` as intended. Closing the issue, thank you for reporting it :)

**Closed by bcdurak** 2024-04-10 13:14 UTC
Labels: bug
