### ISSUE TITLE
[BUG]: InvalidGitRepositoryError when using `kubeflow_pipelines_orchestration` example

### ISSUE THREAD

**Issue by sbakiu** [zenml-io/zenml#773] opened 2022-07-15 20:45 UTC
### System Information

```
ZenML version: 0.10.0
Install path: <path>/.venv/lib/python3.8/site-packages/zenml
Python version: 3.8.9
Platform information: {'os': 'mac', 'mac_version': '12.4'}
Environment: native
Integrations: ['kubeflow', 'kubernetes', 'seldon', 'tensorflow']
```

### What happened?
Following the instructions @ https://github.com/zenml-io/zenml/tree/main/examples/kubeflow_pipelines_orchestration,
running the command `zenml example run kubeflow_pipelines_orchestrator`, throws the following issue:
```
> zenml example pull kubeflow_pipelines_orchestrator
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│                                                       <path>/.venv/bin/zenml:8 in <module>       │
│                                                                                                  │
│   5 from zenml.cli.cli import cli                                                                │
│   6 if __name__ == '__main__':                                                                   │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 8 │   sys.exit(cli())                                                                          │
│   9                                                                                              │
│                                                                                                  │
│                                                       <path>/.venv/lib/python3.8/site-packages/c │
│ lick/core.py:1130 in __call__                                                                    │
│                                                                                                  │
│   1127 │                                                                                         │
│   1128 │   def __call__(self, *args: t.Any, **kwargs: t.Any) -> t.Any:                           │
│   1129 │   │   """Alias for :meth:`main`."""                                                     │
│ ❱ 1130 │   │   return self.main(*args, **kwargs)                                                 │
│   1131                                                                                           │
│   1132                                                                                           │
│   1133 class Command(BaseCommand):                                                               │
│                                                                                                  │
.
.
.
.
.

│ it/repo/base.py:307 in common_dir                                                                │
│                                                                                                  │
│    304 │   │   │   return self.git_dir                                                           │
│    305 │   │   else:                                                                             │
│    306 │   │   │   # or could return ""                                                          │
│ ❱  307 │   │   │   raise InvalidGitRepositoryError()                                             │
│    308 │                                                                                         │
│    309 │   @property                                                                             │
│    310 │   def bare(self) -> bool:                                                               │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
InvalidGitRepositoryError
```

### Reproduction steps

1. Create a new virtual env
2. `pip install zenml`
3. `zenml integration install kubeflow tensorflow`
4. `zenml example pull kubeflow_pipelines_orchestrator`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by htahir1** [comment] 2022-07-16 12:48
Hi @sbakiu sorry that you experienced that. I was not able to do it on my own machine. Are you sure that git is installed on your machine? That perhaps is an undocumented pre-requisite for this example.

zenml example pull basically does the following automatically which you could replicate manually for now:

```
git clone git@github.com:zenml-io/zenml.git
cd zenml/examples/kubeflow_pipelines_orchestrator
```

**Comment by sbakiu** [comment] 2022-07-18 04:48
Hey @htahir1, yes I have `git` installed. Cloning the repo with `git clone` works as expected, but using the wrapper still throws the same issues.
BTW, I am using python3.8

**Comment by sbakiu** [comment] 2022-07-18 05:00
Here is the full error message:
```
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│                                        <path>/.venv/bin/zenml:8 in <module>                      │
│                                                                                                  │
│   5 from zenml.cli.cli import cli                                                                │
│   6 if __name__ == '__main__':                                                                   │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 8 │   sys.exit(cli())                                                                          │
│   9                                                                                              │
│                                                                                                  │
│                                        <path>/.venv/lib/python3.8/site-packages/click/core.py:11 │
│ 30 in __call__                                                                                   │
│                                                                                                  │
│   1127 │                                                                                         │
│   1128 │   def __call__(self, *args: t.Any, **kwargs: t.Any) -> t.Any:                           │
│   1129 │   │   """Alias for :meth:`main`."""                                                     │
│ ❱ 1130 │   │   return self.main(*args, **kwargs)                                                 │
│   1131                                                                                           │
│   1132                                                                                           │
│   1133 class Command(BaseCommand):                                                               │
│                                                                                                  │
│                                        <path>/.venv/lib/python3.8/site-packages/click/core.py:10 │
│ 55 in main                                                                                       │
│                                                                                                  │
│   1052 │   │   try:                                                                              │
│   1053 │   │   │   try:                                                                          │
│   1054 │   │   │   │   with self.make_context(prog_name, args, **extra) as ctx:                  │
│ ❱ 1055 │   │   │   │   │   rv = self.invoke(ctx)                                                 │
│   1056 │   │   │   │   │   if not standalone_mode:                                               │
│   1057 │   │   │   │   │   │   return rv                                                         │
│   1058 │   │   │   │   │   # it's not safe to `ctx.exit(rv)` here!                               │
│                                                                                                  │
│                                        <path>/.venv/lib/python3.8/site-packages/click/core.py:16 │
│ 57 in invoke                                                                                     │
│                                                                                                  │
│   1654 │   │   │   │   super().invoke(ctx)                                                       │
│   1655 │   │   │   │   sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)                    │
│   1656 │   │   │   │   with sub_ctx:                                                             │
│ ❱ 1657 │   │   │   │   │   return _process_result(sub_ctx.command.invoke(sub_ctx))               │
│   1658 │   │                                                                                     │
│   1659 │   │   # In chain mode we create the contexts step by step, but after the                │
│   1660 │   │   # base command has been invoked.  Because at that point we do not                 │
│                                                                                                  │
│                                        <path>/.venv/lib/python3.8/site-packages/click/core.py:16 │
│ 57 in invoke                                                                                     │
│                                                                                                  │
│   1654 │   │   │   │   super().invoke(ctx)                                                       │
│   1655 │   │   │   │   sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)                    │
│   1656 │   │   │   │   with sub_ctx:                                                             │
│ ❱ 1657 │   │   │   │   │   return _process_result(sub_ctx.command.invoke(sub_ctx))               │
│   1658 │   │                                                                                     │
│   1659 │   │   # In chain mode we create the contexts step by step, but after the                │
│   1660 │   │   # base command has been invoked.  Because at that point we do not                 │
│                                                                                                  │
│                                        <path>/.venv/lib/python3.8/site-packages/click/core.py:14 │
│ 04 in invoke                                                                                     │
│                                                                                                  │
│   1401 │   │   │   echo(style(message, fg="red"), err=True)                                      │
│   1402 │   │                                                                                     │
│   1403 │   │   if self.callback is not None:                                                     │
│ ❱ 1404 │   │   │   return ctx.invoke(self.callback, **ctx.params)                                │
│   1405 │                                                                                         │
│   1406 │   def shell_complete(self, ctx: Context, incomplete: str) -> t.List["CompletionItem"]:  │
│   1407 │   │   """Return a list of completions for the incomplete value. Looks                   │
│                                                                                                  │
│                                        <path>/.venv/lib/python3.8/site-packages/click/core.py:76 │
│ 0 in invoke                                                                                      │
│                                                                                                  │
│    757 │   │                                                                                     │
│    758 │   │   with augment_usage_errors(__self):                                                │
│    759 │   │   │   with ctx:                                                                     │
│ ❱  760 │   │   │   │   return __callback(*args, **kwargs)                                        │
│    761 │                                                                                         │
│    762 │   def forward(                                                                          │
│    763 │   │   __self, __cmd: "Command", *args: t.Any, **kwargs: t.Any  # noqa: B902             │
│                                                                                                  │
│                                        <path>/.venv/lib/python3.8/site-packages/click/decorators │
│ .py:73 in new_func                                                                               │
│                                                                                                  │
│    70 │   │   │   ctx = get_current_context()                                                    │
│    71 │   │   │                                                                                  │
│    72 │   │   │   if ensure:                                                                     │
│ ❱  73 │   │   │   │   obj = ctx.ensure_object(object_type)                                       │
│    74 │   │   │   else:                                                                          │
│    75 │   │   │   │   obj = ctx.find_object(object_type)                                         │
│    76                                                                                            │
│                                                                                                  │
│                                        <path>/.venv/lib/python3.8/site-packages/click/core.py:63 │
│ 8 in ensure_object                                                                               │
│                                                                                                  │
│    635 │   │   """                                                                               │
│    636 │   │   rv = self.find_object(object_type)                                                │
│    637 │   │   if rv is None:                                                                    │
│ ❱  638 │   │   │   self.obj = rv = object_type()                                                 │
│    639 │   │   return rv                                                                         │
│    640 │                                                                                         │
│    641 │   @t.overload                                                                           │
│                                                                                                  │
│                                        <path>/.venv/lib/python3.8/site-packages/zenml/cli/exampl │
│ e.py:430 in __init__                                                                             │
│                                                                                                  │
│   427 │   │   self.examples_dir = Path(                                                          │
│   428 │   │   │   os.path.join(self.repo_dir, EXAMPLES_GITHUB_REPO)                              │
│   429 │   │   )                                                                                  │
│ ❱ 430 │   │   self.examples_repo = ExamplesRepo(self.examples_dir)                               │
│   431 │                                                                                          │
│   432 │   @property                                                                              │
│   433 │   def examples(self) -> List[Example]:                                                   │
│                                                                                                  │
│                                        <path>/.venv/lib/python3.8/site-packages/zenml/cli/exampl │
│ e.py:299 in __init__                                                                             │
│                                                                                                  │
│   296 │   │   │   raise GitNotFoundError(e)                                                      │
│   297 │   │                                                                                      │
│   298 │   │   try:                                                                               │
│ ❱ 299 │   │   │   self.repo = Repo(self.cloning_path)                                            │
│   300 │   │   except NoSuchPathError or InvalidGitRepositoryError:                               │
│   301 │   │   │   self.repo = None  # type: ignore                                               │
│   302 │   │   │   logger.debug(                                                                  │
│                                                                                                  │
│                                        <path>/.venv/lib/python3.8/site-packages/git/repo/base.py │
│ :224 in __init__                                                                                 │
│                                                                                                  │
│    221 │   │   │   self._working_tree_dir = None                                                 │
│    222 │   │   # END working dir handling                                                        │
│    223 │   │                                                                                     │
│ ❱  224 │   │   self.working_dir: Optional[PathLike] = self._working_tree_dir or self.common_dir  │
│    225 │   │   self.git = self.GitCommandWrapperType(self.working_dir)                           │
│    226 │   │                                                                                     │
│    227 │   │   # special handling, in special times                                              │
│                                                                                                  │
│                                        <path>/.venv/lib/python3.8/site-packages/git/repo/base.py │
│ :307 in common_dir                                                                               │
│                                                                                                  │
│    304 │   │   │   return self.git_dir                                                           │
│    305 │   │   else:                                                                             │
│    306 │   │   │   # or could return ""                                                          │
│ ❱  307 │   │   │   raise InvalidGitRepositoryError()                                             │
│    308 │                                                                                         │
│    309 │   @property                                                                             │
│    310 │   def bare(self) -> bool:                                                               │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯

```

Seems like the error is coming from here: https://github.com/zenml-io/zenml/blob/main/src/zenml/cli/example.py#L299

**Comment by fa9r** [comment] 2022-07-18 14:33
Another question, do you have a new Mac with M1 chip by any chance?

**Comment by sbakiu** [comment] 2022-07-18 14:43
Hey @fa9r ,

I still get the same issue with the new command. I am using an older Macbook version with an Intel chip.
This was the first time I pulled the examples.

Not sure what is missing. My assumption is that I don't need to clone the repo before being able to pull the examples. Is that correct?

**Comment by fa9r** [comment] 2022-07-18 15:20
Hmm, then I am also not sure what is happening here. Unfortunately, I cannot reproduce the issue. On my machine (M1 Mac) the example is downloaded correctly. I'll ask some of my colleagues with Intel Macs to reproduce this.

In the meanwhile, you could download and run the example manually like this:
- clone the zenml repo
- go to `examples/kubeflow_pipeline_orchestration` 
- follow the guide for running kubeflow locally in the README here: https://github.com/zenml-io/zenml/tree/main/examples/kubeflow_pipelines_orchestration#%EF%B8%8F-run-the-same-pipeline-on-a-local-kubeflow-pipelines-deployment
- (or, alternatively, follow the jupyter notebook in the same folder)

FYI what happens when you call `zenml examples run` under the hood is that we clone the zenml repo into your global config directory (on Mac), go to the respective example in the `examples/` folder, prepare the environment according to `setup.sh` and then run `run.py` (which would do the same as the manual run above, just a bit more conveniently :))

**Comment by sbakiu** [comment] 2022-07-18 16:43
yeah, no worries. I can work around that

**Comment by htahir1** [comment] 2022-07-25 06:11
@sbakiu As we could not reproduce this issue, I would ask that we close it and re-open it in case someone else encounters the same

**Closed** 2022-07-29 15:08 UTC
Labels: bug
