### ISSUE TITLE
[BUG]: Version 0.8.1 (Py39) is incompatible with the latest version of bunch other packages

### ISSUE THREAD

**Issue by amirhessam88** [zenml-io/zenml#650] opened 2022-05-25 23:16 UTC
### System Information

Python 3.9.7 64-bit
MacOS BigSur v 11.6.5

### What happened?

@htahir1  Thanks for the Python 3.9 release. I am aware that the issues below are out of your control and somehow I can make this issue work (check the examples below) on my side, however, since you guys are using `poetry` (same as me) that would be better to  check the `poetry.lock` file in the repo. I also raise this here so we all can escalate the issues so the related packages upgrade their dependencies too.
Thanks. Amir ...

Example 1:
```
Because no versions of zenml match >0.8.1,<0.9.0
   and zenml (0.8.1) depends on ml-pipelines-sdk (1.8.0rc1), zenml (>=0.8.1,<0.9.0) requires ml-pipelines-sdk (1.8.0rc1).
  And because ml-pipelines-sdk (1.8.0rc1) depends on packaging (>=20,<21), zenml (>=0.8.1,<0.9.0) requires packaging (>=20,<21).
  And because statsmodels (0.13.2) depends on packaging (>=21.3)
   and no versions of statsmodels match >0.13.2,<0.14.0, zenml (>=0.8.1,<0.9.0) is incompatible with statsmodels (>=0.13.2,<0.14.0).
```

Example 2:
```
Because no versions of zenml match >0.8.1,<0.9.0
   and zenml (0.8.1) depends on ml-pipelines-sdk (1.8.0rc1), zenml (>=0.8.1,<0.9.0) requires ml-pipelines-sdk (1.8.0rc1).
      And because ml-pipelines-sdk (1.8.0rc1) depends on ml-metadata (>=1.8.0,<1.9.0), zenml (>=0.8.1,<0.9.0) requires ml-metadata (>=1.8.0,<1.9.0).
      Because ml-metadata (1.8.0) depends on attrs (>=20.3,<21)
   and no versions of ml-metadata match >1.8.0,<1.9.0, ml-metadata (>=1.8.0,<1.9.0) requires attrs (>=20.3,<21).
  (1) Thus, zenml (>=0.8.1,<0.9.0) requires attrs (>=20.3,<21).

```

Example 3:
```
Because requests-cache (0.9.3) depends on attrs (>=21.2,<22.0)
   and no versions of requests-cache match >0.9.3,<0.9.4 || >0.9.4,<0.10.0, requests-cache (>=0.9.3,<0.9.4 || >0.9.4,<0.10.0) requires attrs (>=21.2,<22.0).
      And because requests-cache (0.9.4) depends on attrs (>=21.2,<22.0), requests-cache (>=0.9.3,<0.10.0) requires attrs (>=21.2,<22.0).
      And because zenml (>=0.8.1,<0.9.0) requires attrs (>=20.3,<21) (1), zenml (>=0.8.1,<0.9.0) is incompatible with requests-cache (>=0.9.3,<0.10.0)

```

### Reproduction steps

1.
2.
3.
...

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by htahir1** [comment] 2022-05-27 09:38
Thanks @amirhessam88 ! Did you get this via `pip` or `poetry`? We only use poetry for internal development, but recommend using pip to install the package itself. Via pip I cannot reproduce this issue. Can you let me know reproduction steps?

**Comment by amirhessam88** [comment] 2022-05-27 14:35
@htahir1 sure; and yes; I do use `poetry`; Let's say you have an environment with 2 packages installed, something like below:
```
[tool.poetry.dependencies]
python = ">=3.9,<3.10"

statsmodels = "^0.13.2"
requests-cache = "^0.9.3"

```
then,  you would like add `zenml`; so you run:
```
poetry add zenml
```
.... and then you get the errors; I did fix the `statsmodels` one by downgrading to version `0.12.1` since the clash is related to `packaging` library; however, the conflicts regarding the `attrs` version could not be solved unless the `ml-metadata`, and accordingly `ml-pipelines-sdk`, (or any upstream libraries) change their `attrs` version so the downstream libraries would work normally.

FYI, I did also the reverse process; I have an evironment setup with **ONLY** `zenml` and tried to install the above-mentioned libraries; and you should also see the same errors. 

```
[tool.poetry.dependencies]
python = ">=3.9,<3.10"
zenml = "^0.8.1"

```
So, I took a look at the `poetry.lock` file of my `zenml` environment; here are `attrs` related pieces:
```
[[package]]
name = "attrs"
version = "20.3.0"
description = "Classes Without Boilerplate"
category = "main"
optional = false
python-versions = ">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*"

[package.dependencies]
absl-py = ">=0.9,<2.0.0"
attrs = ">=20.3,<21"
grpcio = ">=1.8.6,<2"
protobuf = ">=3.13,<4"
six = ">=1.10,<2"

```
This part `attrs = ">=20.3,<21"` will halt installation of attrs version > 21 which makes conflicts with bunch of packages.

Here is the `requirements.txt` populated via `poetry export` out of my environment with only `zenml` setup.

```
absl-py==1.0.0; python_version >= "3.7" and python_version < "3.10" and python_full_version >= "3.7.1"
analytics-python==1.4.0; python_full_version >= "3.7.1" and python_version < "3.10"
anyio==3.6.1; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7"
apache-beam==2.39.0; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7"
appnope==0.1.3; python_full_version >= "3.7.1" and python_full_version < "4.0.0" and python_version < "3.10" and python_version >= "3.8" and platform_system == "Darwin" and sys_platform == "darwin"
argon2-cffi-bindings==21.2.0; python_full_version >= "3.7.1" and python_full_version < "4.0.0" and python_version < "3.10" and python_version >= "3.7"
argon2-cffi==21.3.0; python_full_version >= "3.7.1" and python_full_version < "4.0.0" and python_version < "3.10" and python_version >= "3.7"
asgiref==3.5.2; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7"
asttokens==2.0.5; python_full_version >= "3.7.1" and python_full_version < "4.0.0" and python_version < "3.10" and python_version >= "3.8"
attrs==20.3.0; python_version >= "3.7" and python_version < "3.10" and python_full_version >= "3.7.1"
backcall==0.2.0; python_full_version >= "3.7.1" and python_full_version < "4.0.0" and python_version < "3.10" and python_version >= "3.8"
backoff==1.10.0; python_full_version >= "3.7.1" and python_version < "3.10"
beautifulsoup4==4.11.1; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7"
bleach==5.0.0; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7"
cachetools==5.1.0; python_version >= "3.7" and python_version < "3.10" and python_full_version >= "3.7.1"
certifi==2022.5.18.1; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.6"
cffi==1.15.0; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7" and implementation_name == "pypy" and python_full_version < "4.0.0"
charset-normalizer==2.0.12; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3"
click-params==0.3.0; python_version >= "3.7" and python_version < "3.10" and python_full_version >= "3.7.1"
click==8.1.3; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7"
cloudpickle==2.1.0; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7"
colorama==0.4.4
commonmark==0.9.1; python_full_version >= "3.7.1" and python_full_version < "4.0.0" and python_version < "3.10"
crcmod==1.7; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7"
debugpy==1.6.0; python_full_version >= "3.7.1" and python_full_version < "4.0.0" and python_version < "3.10" and python_version >= "3.7"
decorator==5.1.1; python_version >= "3.8" and python_version < "3.10" and python_full_version >= "3.7.1" and python_full_version < "4.0.0"
defusedxml==0.7.1; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7"
dill==0.3.1.1; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7"
distro==1.7.0; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.6"
docker==4.4.4; python_version >= "3.7" and python_version < "3.10" and python_full_version >= "3.7.1"
docopt==0.6.2; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7"
entrypoints==0.4; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7"
executing==0.8.3; python_full_version >= "3.7.1" and python_full_version < "4.0.0" and python_version < "3.10" and python_version >= "3.8"
fastapi==0.75.2; python_full_version >= "3.7.1" and python_version < "3.10"
fastavro==1.4.12; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7"
fasteners==0.17.3; python_version >= "3.7" and python_version < "3.10" and python_full_version >= "3.7.1"
fastjsonschema==2.15.3; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7"
gitdb==4.0.9; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7"
gitpython==3.1.27; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7"
google-api-core==2.8.1; python_version >= "3.7" and python_version < "3.10" and python_full_version >= "3.7.1"
google-api-python-client==1.12.11; python_version >= "3.7" and python_version < "3.10" and python_full_version >= "3.7.1"
google-apitools==0.5.32; python_version >= "3.7" and python_version < "3.10" and python_full_version >= "3.7.1"
google-auth-httplib2==0.1.0; python_version >= "3.7" and python_version < "3.10" and python_full_version >= "3.7.1"
google-auth==2.6.6; python_version >= "3.7" and python_version < "3.10" and python_full_version >= "3.7.1"
googleapis-common-protos==1.56.2; python_version >= "3.7" and python_version < "3.10" and python_full_version >= "3.7.1"
greenlet==1.1.2; python_version >= "3" and (platform_machine == "aarch64" or platform_machine == "ppc64le" or platform_machine == "x86_64" or platform_machine == "amd64" or platform_machine == "AMD64" or platform_machine == "win32" or platform_machine == "WIN32") and python_full_version >= "3.7.1" and python_full_version < "4.0.0" and python_version < "3.10"
grpcio==1.46.3; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7"
h11==0.13.0; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7"
hdfs==2.7.0; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7"
httplib2==0.19.1; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7"
httptools==0.4.0; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7"
idna==3.3; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.6"
ipykernel==6.13.0; python_full_version >= "3.7.1" and python_full_version < "4.0.0" and python_version < "3.10" and python_version >= "3.7"
ipython-genutils==0.2.0; python_full_version >= "3.7.1" and python_full_version < "4.0.0" and python_version < "3.10" and python_version >= "3.7"
ipython==8.3.0; python_full_version >= "3.7.1" and python_full_version < "4.0.0" and python_version < "3.10" and python_version >= "3.8"
ipywidgets==7.7.0; python_full_version >= "3.7.1" and python_full_version < "4.0.0" and python_version < "3.10"
jedi==0.18.1; python_full_version >= "3.7.1" and python_full_version < "4.0.0" and python_version < "3.10" and python_version >= "3.8"
jinja2==2.11.3; python_version >= "3.7" and python_version < "3.10" and python_full_version >= "3.7.1" and python_full_version < "4.0.0"
jsonschema==4.5.1; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7"
jupyter-client==7.3.1; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7" and python_full_version < "4.0.0"
jupyter-core==4.10.0; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7" and python_full_version < "4.0.0"
jupyterlab-pygments==0.2.2; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7"
jupyterlab-widgets==1.1.0; python_full_version >= "3.7.1" and python_full_version < "4.0.0" and python_version < "3.10" and python_version >= "3.6"
markupsafe==1.1.1; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7"
matplotlib-inline==0.1.3; python_full_version >= "3.7.1" and python_full_version < "4.0.0" and python_version < "3.10" and python_version >= "3.8"
mistune==0.8.4; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7"
ml-metadata==1.8.0; python_version >= "3.7" and python_version < "3.10" and python_full_version >= "3.7.1"
ml-pipelines-sdk==1.8.0rc1; python_version >= "3.7" and python_version < "3.10" and python_full_version >= "3.7.1"
monotonic==1.6; python_full_version >= "3.7.1" and python_version < "3.10"
nbclient==0.5.13; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7"
nbconvert==6.4.4; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7" and python_full_version < "4.0.0"
nbformat==5.4.0; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7" and python_full_version < "4.0.0"
nest-asyncio==1.5.5; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7" and python_full_version < "4.0.0"
notebook==6.4.11; python_full_version >= "3.7.1" and python_full_version < "4.0.0" and python_version < "3.10" and python_version >= "3.7"
numpy==1.22.4
oauth2client==4.1.3; python_version >= "3.7" and python_version < "3.10" and python_full_version >= "3.7.1"
orjson==3.6.8; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7"
packaging==20.9; python_version >= "3.7" and python_version < "3.10" and python_full_version >= "3.7.1" and python_full_version < "4.0.0"
pandas==1.4.2; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.8"
pandocfilters==1.5.0; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7"
parso==0.8.3; python_full_version >= "3.7.1" and python_full_version < "4.0.0" and python_version < "3.10" and python_version >= "3.8"
pexpect==4.8.0; python_full_version >= "3.7.1" and python_full_version < "4.0.0" and python_version < "3.10" and python_version >= "3.8" and sys_platform != "win32"
pickleshare==0.7.5; python_full_version >= "3.7.1" and python_full_version < "4.0.0" and python_version < "3.10" and python_version >= "3.8"
portpicker==1.5.0; python_version >= "3.7" and python_version < "3.10" and python_full_version >= "3.7.1"
prometheus-client==0.14.1; python_full_version >= "3.7.1" and python_full_version < "4.0.0" and python_version < "3.10" and python_version >= "3.7"
prompt-toolkit==3.0.29; python_full_version >= "3.7.1" and python_full_version < "4.0.0" and python_version < "3.10" and python_version >= "3.8"
proto-plus==1.20.5; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7"
protobuf==3.20.1; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7"
psutil==5.9.1; python_version >= "3.7" and python_version < "3.10" and python_full_version >= "3.7.1" and python_full_version < "4.0.0"
ptyprocess==0.7.0; python_full_version >= "3.7.1" and python_full_version < "4.0.0" and python_version < "3.10" and python_version >= "3.8" and sys_platform != "win32" and os_name != "nt"
pure-eval==0.2.2; python_full_version >= "3.7.1" and python_full_version < "4.0.0" and python_version < "3.10" and python_version >= "3.8"
py==1.11.0; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7" and implementation_name == "pypy"
pyarrow==7.0.0; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7"
pyasn1-modules==0.2.8; python_version >= "3.7" and python_version < "3.10" and python_full_version >= "3.7.1"
pyasn1==0.4.8; python_version >= "3.7" and python_version < "3.10" and python_full_version >= "3.7.1"
pycparser==2.21; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7" and implementation_name == "pypy"
pydantic==1.9.1; python_full_version >= "3.7.1" and python_version < "3.10" and python_full_version < "4.0.0"
pydot==1.4.2; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7"
pygments==2.12.0; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.8" and python_full_version < "4.0.0"
pymongo==3.12.3; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7"
pyparsing==2.4.7; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7"
pyrsistent==0.18.1; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7"
python-dateutil==2.8.2; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.8"
python-dotenv==0.20.0; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7"
pytz==2022.1; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.8"
pywin32==227; python_version >= "3.7" and python_version < "3.10" and python_full_version >= "3.7.1" and sys_platform == "win32" and platform_python_implementation != "PyPy"
pywinpty==2.0.5; python_full_version >= "3.7.1" and python_full_version < "4.0.0" and python_version < "3.10" and python_version >= "3.7" and os_name == "nt"
pyyaml==5.4.1; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7"
pyzmq==23.0.0; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7" and python_full_version < "4.0.0"
requests==2.27.1; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7"
rich==12.4.4; python_full_version >= "3.7.1" and python_full_version < "4.0.0" and python_version < "3.10"
rsa==4.8; python_version >= "3.7" and python_version < "3.10" and python_full_version >= "3.7.1"
semver==2.13.0; python_full_version >= "3.7.1" and python_version < "3.10"
send2trash==1.8.0; python_full_version >= "3.7.1" and python_full_version < "4.0.0" and python_version < "3.10" and python_version >= "3.7"
six==1.16.0; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.8" and python_full_version < "4.0.0"
smmap==5.0.0; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7"
sniffio==1.2.0; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.6"
soupsieve==2.3.2.post1; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7"
sqlalchemy2-stubs==0.0.2a22; python_full_version >= "3.7.1" and python_full_version < "4.0.0" and python_version < "3.10" and python_version >= "3.6"
sqlalchemy==1.4.36; python_full_version >= "3.7.1" and python_full_version < "4.0.0" and python_version < "3.10"
sqlmodel==0.0.6; python_full_version >= "3.7.1" and python_full_version < "4.0.0" and python_version < "3.10"
stack-data==0.2.0; python_full_version >= "3.7.1" and python_full_version < "4.0.0" and python_version < "3.10" and python_version >= "3.8"
starlette==0.17.1; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.6"
terminado==0.15.0; python_full_version >= "3.7.1" and python_full_version < "4.0.0" and python_version < "3.10" and python_version >= "3.7"
testpath==0.6.0; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7"
tornado==6.1; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7" and python_full_version < "4.0.0"
traitlets==5.2.1.post0; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.8" and python_full_version < "4.0.0"
typing-extensions==4.2.0; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7" and python_full_version < "4.0.0"
uritemplate==3.0.1; python_version >= "3.7" and python_version < "3.10" and python_full_version >= "3.7.1"
urllib3==1.26.9; python_full_version >= "3.7.1" and python_version < "3.10"
uvicorn==0.17.6; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7"
uvloop==0.16.0; sys_platform != "win32" and sys_platform != "cygwin" and platform_python_implementation != "PyPy" and python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7"
validators==0.18.2; python_version >= "3.7" and python_version < "3.10" and python_full_version >= "3.7.1"
watchgod==0.8.2; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7"
wcwidth==0.2.5; python_full_version >= "3.7.1" and python_full_version < "4.0.0" and python_version < "3.10" and python_version >= "3.8"
webencodings==0.5.1; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7"
websocket-client==1.3.2; python_version >= "3.7" and python_version < "3.10" and python_full_version >= "3.7.1"
websockets==10.3; python_full_version >= "3.7.1" and python_version < "3.10" and python_version >= "3.7"
widgetsnbextension==3.6.0; python_full_version >= "3.7.1" and python_full_version < "4.0.0" and python_version < "3.10"
zenml==0.8.1; python_full_version >= "3.7.1" and python_version < "3.10"

```
where `attrs==20.3.0; python_version >= "3.7" and python_version < "3.10" and python_full_version >= "3.7.1"` been installed.

Hope this helps.

**Comment by htahir1** [comment] 2022-05-30 10:17
Thank you that was indeed  very helpful! Unfortunately, as you already said in your first message, this is out of our control. `ml-pipelines-sdk` is a core dependency and we can't easily get rid of it (yet). Therefore, unless they change their `attrs` and `packaging` requirements we are unable to support your request for now. 

Is there a way you can simply conform to the attrs and packaging constraints specified?

**Comment by htahir1** [comment] 2022-06-07 08:29
Closing this issue due to staleness. Feel free to open it again if there is an update

**Closed by htahir1** 2022-06-07 08:29 UTC
Labels: bug
